name: mydexpogo
description: "simple pokedex for pokemongo for you to create your own lists to track what you didn't catch yet"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # For Localization
    sdk: flutter
  intl: ^0.19.0 # Or latest, for localization generation

    # State Management
  flutter_riverpod: ^2.5.1 # Or latest

    # Networking
  http: ^1.2.1 # Or latest

    # JSON Parsing
  json_annotation: ^4.9.0 # Or latest

    # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

    # Image Caching
  cached_network_image: ^3.3.1 # Or latest

    # File Handling & Sharing
  file_picker: ^8.0.3 # Or latest
  path_provider: ^2.1.3 # Or latest
  share_plus: ^9.0.0 # Or latest
  clipboard: ^0.1.3 # Or latest
  permission_handler: ^11.3.1 # For Android storage permissions if needed

    # Utilities
  collection: ^1.18.0 # Or latest (for firstWhereOrNull etc.)
    # url_launcher: ^6.2.6 # Potentially useful for opening links


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Recommended for code analysis

  build_runner: ^2.4.9 # Or latest
  json_serializable: ^6.8.0 # Or latest
  hive_generator: ^2.0.1


flutter:
  uses-material-design: true
  generate: true
